server:
  port: 8761
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: eureka-discovery-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
